import csv
import json
import os

CSV_FILE = 'generic_medicines_dataset.csv'
JSON_FILE = 'medicines_data.json'

print(f"🔄 converting and RESTRUCTURING {CSV_FILE} into {JSON_FILE}...")

if not os.path.exists(CSV_FILE):
    print(f"🛑 Error: Couldn't find '{CSV_FILE}'.")
    print("   If you already have 'medicines_data.json' generated by mimip.py, you don't need this script!")
    exit()

# We will transform the flat CSV list into a structured dictionary
# Structure: { "BrandName": { "active_ingredient": "...", "alternatives": [...] } }
structured_data = {}

try:
    with open(CSV_FILE, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            brand = row['Brand_Name']
            product = row['Product_Name']
            manufacturer = row['Manufacturer']
            ingredient = row['Active_Ingredients']

            # 1. Initialize the brand entry if it's new
            if brand not in structured_data:
                structured_data[brand] = {
                    "active_ingredient": ingredient,
                    "alternatives": []
                }

            # 2. Add data based on type
            if manufacturer == "Original":
                # Ensure the ingredient is set correctly from the source
                structured_data[brand]["active_ingredient"] = ingredient
            else:
                # It's a generic alternative, add it to the list
                # Avoid duplicates
                exists = any(alt['product_name'] == product for alt in structured_data[brand]['alternatives'])
                if not exists:
                    structured_data[brand]['alternatives'].append({
                        "product_name": product,
                        "manufacturer": manufacturer
                    })
    
    # 3. Save as the new standard JSON format
    with open(JSON_FILE, 'w', encoding='utf-8') as f:
        json.dump(structured_data, f, indent=4)
        
    print(f"✅ Success! Your old CSV data has been migrated to the new format in {JSON_FILE}.")
    print("   You can now run 'offline_app.py' or 'recommender.py' immediately.")

except Exception as e:
    print(f"🛑 An error occurred during conversion: {e}")